#CSE 101: Computer Science Principles
####Stony Brook University, Summer 2020

### Homework Assignment #2

#### Due: Sunday, June 7th 2020 at 11:59 pm EDT

#### Learning Outcomes
By the end of these exercises you should be able to:
* Write short code fragments that use if-statements:
    * with only an if-clause
    * with an if-clause and an else-clause
    * with an if-clause and one or more elif-clauses
* Write functions that perform simple mathematical computations.

#### Part 1: Evaluate a Piecewise Function (10 points)

Complete the function `piecewise`, which returns the value of the mathematical function below. The values of $x$ and $y$ are taken as arguments to the function.

$f(x,y) = 
\begin{cases} 
x-2y & x\leq 0 \\[12pt]
\frac{1-y}{x} & 0 < x\leq 10 \\[12pt]
\frac{(y+1)^2}{x^3} & x > 10
\end{cases}
$

Expected Results:

Function Call | Return Value
:-- | :--
`piecewise(5.00, 0.60)` | `0.08`
`piecewise(2.12, 7.00)` | `-2.830188679245283`
`piecewise(-9.50, -4.88)` | `0.2599999999999998`
`piecewise(12.75, -31.20)` | `0.4400310589441467`
`piecewise(-3.00, 5.00)` | `-13.0`

In [0]:
def piecewise(x, y):
    if x <= 0:
        result = x-2*y
    elif x <= 10:
        result = (1-y)/x
    else:
        result = (y+1)**2/x**3
    return result

# Test cases
print(piecewise(5.00, 0.60))
print(piecewise(2.12, 7.00))
print(piecewise(-9.50, -4.88))
print(piecewise(12.75, -31.20))
print(piecewise(-3.00, 5.00))

0.08
-2.830188679245283
0.2599999999999998
0.4400310589441467
-13.0

#### Part 2: Update Your Gas Rewards Card Balance (20 points)

Complete the function `gas_reward`, which returns the new balance for a customer participating in a gas rewards program at a national gas station chain. The function takes three arguments:

* `current_points`: the current rewards points (an integer) on the customer's gas rewards card
* `gas_type`: the type of gasoline purchased (a string), which is one of the following:
   * `'regular'`: \$2.95 / gallon
   * `'plus'`: \$3.10 / gallon
   * `'premium'`: \$3.50 / gallon
* `money_spent`: the amount of dollars spent on gas for a particular transaction. This number is needed to compute how many gallons of gas were purchased.   

The new gas points total is computed according to these rules:

* If *at least* 10 gallons of gas were purchased, the customer is awarded 400 reward points.
* If *at least* 8 gallons of gas were purchased, the customer is awarded 250 reward points.
* If *at least* 5 gallons of gas were purchased, the customer is awarded 100 reward points.
* Otherwise, the customer is awarded 50 reward points.

Expected Results

Function Call | Return Value
:-- | :--
`gas_reward(416, 'regular', 10)` | `466`
`gas_reward(124, 'regular', 20)` | `224`
`gas_reward(21, 'regular', 25)` | `271`
`gas_reward(413, 'regular', 35)` | `813`
`gas_reward(491, 'plus', 11)` | `541`
`gas_reward(345, 'plus', 22)` | `445`
`gas_reward(54, 'plus', 28)` | `304`
`gas_reward(10, 'plus', 37)` | `410`
`gas_reward(24, 'premium', 8)` | `74`
`gas_reward(436, 'premium', 23)` | `536`
`gas_reward(190, 'premium', 30)` | `440`
`gas_reward(290, 'premium', 40)` | `690`

In [0]:
def gas_reward(current_points, gas_type, money_spent):
    if gas_type == 'regular':
        gallons_purchased = money_spent/2.95
    elif gas_type == 'plus':
        gallons_purchased = money_spent/3.10
    elif gas_type == 'premium':
        gallons_purchased = money_spent/3.50

    if gallons_purchased >= 10:
        current_points += 400
    elif gallons_purchased >= 8:
        current_points += 250
    elif gallons_purchased >= 5:
        current_points += 100
    else:
        current_points += 50
    return current_points
    

# Test cases
print(gas_reward(416, 'regular', 10))
print(gas_reward(124, 'regular', 20))
print(gas_reward(21, 'regular', 25))
print(gas_reward(413, 'regular', 35))
print(gas_reward(491, 'plus', 11))
print(gas_reward(345, 'plus', 22))
print(gas_reward(54, 'plus', 28))
print(gas_reward(10, 'plus', 37))
print(gas_reward(24, 'premium', 8))
print(gas_reward(436, 'premium', 23))
print(gas_reward(190, 'premium', 30))
print(gas_reward(290, 'premium', 40))

466
224
271
813
541
445
304
410
74
536
440
690

#### Part 3: Determine the Ending Time (20 points)

Complete the function `ending_time` that determines the final clock time after a task has been completed. The function takes three arguments that provide the current time of day, as well as the total time in seconds that it will
take to complete the task:
1. `hour`: the current hour of the day (0 - 23)
2. `minute`: the current minute of the day (0 - 59)
3. `second`: the current second of the day (0 - 59)
4. `time_taken`: the number of seconds it will take to complete the task (greater than 0)

Assume all inputs are valid. `time_taken` can be arbitrarily large!

As an example, consider the test case: 2, 59, 40, 22. This means that the current hour is 2, the current minute is 59, the current second is 40, and the time to complete the task is 22 seconds. So the first three function arguments represent the time 2:59:40 am.

Adding `time_taken` to the current `second` value updates the `second` value to 62. Because 62 seconds is $\ge$ 60 (i.e., at least one minute), the current `second` value is updated to 2. The `minute` value must also be incremented
by 1 minute, to 60. Similar to how we handled the `second` value, the `minute` value is set to zero because we have a whole new hour. Finally, the `hour` value must be incremented by 1 because `minute` rolled over from 59 to 60
and then to 0. This produces the final result of 3, 0, and 2 for `hour`, `minute` and `second`, respectively.

The return value of the function is an f-string given in this format: `'hh:mm:ss'`, where `hh` gives the two-digit, updated hour; `mm` gives the two-digit, updated minute; and `ss` gives the updated second. 

Hint: the f-string `f'{num:02d}` will display the integer `num` to two digits.

Expected Results

Function Call | Return Value
:-- | :--
`ending_time(2, 59, 40, 22)` | `'03:00:02'`
`ending_time(5, 11, 24, 6)` | `'05:11:30'`
`ending_time(4, 11, 25, 236)` | `'04:15:21'`
`ending_time(11, 54, 56, 340)` | `'12:00:36'`
`ending_time(22, 52, 48, 8000)` | `'01:06:08'`
`ending_time(17, 17, 5, 31688)` | `'02:05:13'`
`ending_time(19, 6, 53, 7500)` | `'21:11:53'`
`ending_time(20, 34, 35, 26770)` | `'04:00:45'`
`ending_time(19, 54, 3, 15463)` | `'00:11:46'`
`ending_time(18, 21, 35, 100000000)` | `'04:08:15'`

In [0]:
def ending_time(hour, minute, second, time_taken):
    
    second += time_taken
    if second >= 60:
        minute += second // 60
        second = second % 60
        
    if minute >= 60:
        hour += minute // 60
        minute = minute % 60
        
    if hour >= 24:
        hour = hour % 24

    time = f'{hour:02d}:{minute:02d}:{second:02d}'

    return time

# Test cases
print(ending_time(2, 59, 40, 22))
print(ending_time(5, 11, 24, 6))
print(ending_time(4, 11, 25, 236))
print(ending_time(11, 54, 56, 340))
print(ending_time(22, 52, 48, 8000))
print(ending_time(17, 17, 5, 31688))
print(ending_time(19, 6, 53, 7500))
print(ending_time(20, 34, 35, 26770))
print(ending_time(19, 54, 3, 15463))
print(ending_time(18, 21, 35, 100000000))

03:00:02
05:11:30
04:15:21
12:00:36
01:06:08
02:05:13
21:11:53
04:00:45
00:11:46
04:08:15

### Part 4: Reformat a Date/Time String

Complete the function `reformat_date`, which takes a string which represents a "datetime" and returns a string that represents the datetime in a different format.

Input format: month day, year time AM/PM

Output format: YYYY-MMM-DD HH:MM

The input date is given in the format typically used in everyday speech and writing: the full name of the month, followed by the day of the month, followed by a comma, and ending with the four-digit year. The output date should be given as a four-digit year, followed by a dash, followed by the first three letters of the month in uppercase, followed by a dash, followed by exactly two digits for the day.

The input time uses AM/PM format. The output time must use 24-hour time with exactly two digits each for the hours and minutes.

Example:
* input: January 3, 2019 5:45 PM
* output: 2019-JAN-03 17:45

Expected Results

Function Call | Return Value
:-- | :--
`reformat_date('January 10, 2019 05:45:49 AM')` | `'2019-JAN-10 05:45'`
`reformat_date('February 06, 2017 7:30:09 AM')` | `'2017-FEB-06 07:30'`
`reformat_date('May 17, 1997 9:30:00 PM')` | `'1997-MAY-17 21:30'`
`reformat_date('June 01, 1996 12:00:00 AM')` | `'1996-JUN-01 00:00'`
`reformat_date('December 12, 2012 10:00:00 PM')` | `'2012-DEC-12 22:00'`
`reformat_date('March 15, 1994 12:00:00 PM')` | `'1994-MAR-15 12:00'`
`reformat_date('April 10, 1995 01:30:49 AM')` | `'1995-APR-10 01:30'`
`reformat_date('July 01, 2000 11:25:00 PM')` | `'2000-JUL-01 23:25'`
`reformat_date('August 15, 1947 12:30:00 AM')` | `'1947-AUG-15 00:30'`
`reformat_date('January 26, 2019 12:55:20 PM')` | `'2019-JAN-26 12:55'`

In [0]:
def reformat_date(dt):
    numbers = ''
    
    for c in dt:    
        if c.isdigit():
            numbers += c

    year = numbers[2:6]
    month = dt[:3].upper()
    day = numbers[:2]
    time = numbers[numbers.find(year)+4:-2]

    if len(time) != 4:
        time = "0" + time
    
    hour = time[:2]
    minute = time[2:4]

    if dt[-2] == "P" and int(hour) < 12:
        hour = int(hour)+12

    elif dt[-2] == "A" and int(hour) == 12:
        hour = '00'

    datetime = f'{year}-{month}-{day} {hour}:{minute}'

    return datetime
    


# Test cases
print(reformat_date('January 10, 2019 05:45:49 AM'))
print(reformat_date('February 06, 2017 7:30:09 AM'))
print(reformat_date('May 17, 1997 9:30:00 PM'))
print(reformat_date('June 01, 1996 12:00:00 AM'))
print(reformat_date('December 12, 2012 10:00:00 PM'))
print(reformat_date('March 15, 1994 12:00:00 PM'))
print(reformat_date('April 10, 1995 01:30:49 AM'))
print(reformat_date('July 01, 2000 11:25:00 PM'))
print(reformat_date('August 15, 1947 12:30:00 AM'))
print(reformat_date('January 26, 2019 12:55:20 PM'))

2019-JAN-10 05:45
2017-FEB-06 07:30
1997-MAY-17 21:30
1996-JUN-01 00:00
2012-DEC-12 22:00
1994-MAR-15 12:00
1995-APR-10 01:30
2000-JUL-01 23:25
1947-AUG-15 00:30
2019-JAN-26 12:55

#### Part 5: In the Money (20 points)

Complete the function `transactions`, which takes two arguments: a string of characters called `sequence` consisting of arithmetical operators and single-digit integers, and an integer `balance` that represent a bank account's starting balance. The `sequence` argument represents a series of financial transactions on a bank account. For example, `'-4`' represents a withdrawal of \$4. The function returns *two values*: the number of transactions performed and the final bank balance based on the transactions performed on the starting bank balance.

Returning two values from a function is easy: just type `return`, followed by the two values separated by a comma. For example, you could type `return message, total`, where `message` and `total` are assumed to be variable names.

The characters in the input string consist of operations and amounts associated with each operation. It is guaranteed that each operation is followed by a one-digit number.

Notes:

* `+` denotes a deposit
* `-` denotes a withdrawal
* The `int` function can convert a digit character into an integer. For instance, suppose `digit` is a variable that contains the string `'8'`. Then, `int(digit)` will return the integer `8`.
* If the starting balance is $\le$ 0, return `'Invalid starting balance'`.
* If a transaction symbol other than `+` or `-` is provided, return `'Invalid transactions'`.
* If, at any point in time, the balance goes below zero, the transactions should be terminated and the function should return: (i) the index at which the termination occurred, followed be (ii) the bank balance at the point before it went below zero.
* If the final bank balance (after successful completion of the transactions) is at least twice the starting balance, then a bonus amount should be added. The bonus amount should be half of starting balance. Use the `//` operator to compute the bonus.

Expected Results

Function Call | Return Value
:-- | :--
`transactions('*1-9', 5)` | `'Invalid transactions'`
`transactions('+9+8-8-3-4-5-1-6', 50)` | `(8, 40)`
`transactions('-4+7', 0)` | `'Invalid starting balance'`
`transactions('+3-8+6+2-7-2-1', 25)` | `(7, 18)`
`transactions('+3-8*2', 25)` | `'Invalid transactions'`
`transactions('+3+1', 4)` | `(2, 10)`
`transactions('+1-9-2-2', 3)` | `(2, 4)`

In [0]:
def transactions(sequence, balance):
    symbol = '+-123456789'
    transaction = 0
    final_balance = balance

    if balance <= 0:
        return 'Invalid starting balance'

    for c in sequence:
        if c not in symbol:
            return 'Invalid transactions'
    else:
        for i in range(len(sequence)):
            if balance < 0:
                return transaction, final_balance

            elif sequence[i] == '+':
                transaction += 1
                final_balance += int(sequence[i+1])
                

            elif sequence[i] == '-':
                transaction += 1
                if int(sequence[i+1]) > balance:
                    return transaction, final_balance
                final_balance -= int(sequence[i+1])

        if final_balance == balance*2:
            final_balance += balance//2


    return transaction, final_balance
            


# Test cases
print(transactions('*1-9', 5))  
print(transactions('+9+8-8-3-4-5-1-6', 50))  
print(transactions('-4+7', 0))  
print(transactions('+3-8+6+2-7-2-1', 25))
print(transactions('+3-8*2', 25))  
print(transactions('+3+1', 4))  
print(transactions('+1-9-2-2', 3))

Invalid transactions
(8, 40)
Invalid starting balance
(7, 18)
Invalid transactions
(2, 10)
(2, 4)

### How to Submit Your Work

1. Go to the [course website](https://sites.google.com/stonybrook.edu/cse-101/schedule?authuser=0).

1. Click the **Submit** link for this assignment.

1. Type your SBU ID# on the line provided.

1. Press the button marked **Add file**.

1. Click the **My Drive** tab.

1. Click on the file you wish to submit.

1. Hit **Select**.

1. Hit **Submit** to submit your file grading.